### ISSUE TITLE
当前失效了，天翼云盘修改了链接

### ISSUE THREAD

**Issue by rusellwo** [YafengLiang/Check189#1]
captchaToken = re.findall(r"captchaToken' value='(.+?)'", r.text)[0]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by YafengLiang** [comment]
确实，他现在走了oauth2
`https://api.cloud.189.cn/open/oauth2/ssoH5.action?scene=`
![image](https://github.com/YafengLiang/Check189/assets/30494177/edba41e6-d3a5-4e4f-be61-2beeaf9fa134)

**Comment by YafengLiang** [comment]
现已换了代码，可正常运行
