### ISSUE TITLE
大佬，Server酱推送显示errorCode？

### ISSUE THREAD

**Issue by aldinwilson** [YafengLiang/Check189#6]
![image](https://github.com/YafengLiang/Check189/assets/74028571/a9b2785a-d24a-40be-b0b8-592908016ce4)

**Comment by YafengLiang** [comment]
这是推送了两次还是怎么了？
`
2023-11-13 01:19:53 Monday

账号：178****9198

密码：登录成功

已经签到过了，签到获得92M空间

抽奖获得1

抽奖获得1

链接3抽奖获得1

今日免费额度:1/5 · [可访问 sct.ftqq.com 购买或续期订阅会员](https://sct.ftqq.com/donate)
`
我查了下历史推送记录，有时候确实会提示错误，原因是我手动执行了一遍，后续自动又执行一遍，导致抽奖的链接失效（每天只允许一次）的错误提示
